-- JK AGENDA DE VISITAS - GRUPO AG - COMANDOS DRL PARA RECUPERAÇÃO DE DADOS

-- RETORNAR PROPRIETÁRIOS

SELECT
    PR.CD_PROP "CD PROPRIETARIO",
    RTRIM(LTRIM(PR.NM_PROP)) "NOME",
        CASE  
        WHEN PR.GENERO_NASC = 'M' THEN 'MASCULINO'
        WHEN PR.GENERO_NASC = 'F' THEN 'FEMININO'
        ELSE 'NÃO IDENTIFICADO' END "GÊNERO",
    NVL(PR.QUALIFICACAO, 'NÃO IDENTIFICADO') "QUALIFICAÇÃO",
    NVL(PR.EMAIL, 'NÃO IDENTIFICADO') "EMAIL",
    NVL(FN.NR_FONE, 'NÃO IDENTIFICADO') "TELEFONE"
    
FROM T_JK_PROP PR
    LEFT JOIN T_JK_FONE_PROP FNP ON (PR.CD_PROP = FNP.CD_PROP)
    LEFT JOIN T_JK_FONE FN ON (FN.CD_FONE = FNP.CD_FONE)
    ORDER BY PR.CD_PROP ASC;

--RETORNAR EMPRESAS E RESPECTIVOS ENDEREÇOS, TELEFONES E RAMOS

SELECT DISTINCT  
         EMP.CD_EMPRESA "CD EMPRESA",
         EMP.CNPJ_EMP CNPJ,
         EMP.RZ_SOCIAL "RAZÃO SOCIAL",
         NVL(EMP.NM_FANTASIA,'NÃO IDENTIFICADO') "NOME FANTASIA",
         '(' || RTRIM(FN.NR_DDD) || ')' || FN.NR_FONE TELEFONE,
         EMP.DT_FUNDACAO "DT FUNDAÇÃO",
         EMP.SITE "SITE",
         EMP.PORTE "PORTE",
         RM.NM_RAMO "RAMO",
         RM.NR_RAMO "NR RAMO",
         EMP.ENT_CLIENTE "CLIENTE/PROSPECÇÃO",
         EST.NM_ESTADO ESTADO,
         CID.NM_CIDADE CIDADE,
         RTRIM(LTRIM(BAI.NM_BAIRRO)) BAIRRO,
         LOGR.NM_LOGRADOURO LOGRADOURO,
         TO_CHAR(SUBSTR( LOGR.NR_CEP , 1 , 2 ) || '.' || substr( LOGR.NR_CEP , 3 , 3) || '-' || substr( LOGR.NR_CEP , 6 , length(LOGR.NR_CEP))) AS CEP,
         ENDEMP.NR_ENDERECO NÚMERO,
         ENDEMP.STATUS STATUS,
         ENDEMP.DT_INICIO "DATA INÍCIO"
         
FROM T_JK_EMPRESA EMP
    LEFT JOIN T_JK_ENDERECO_EMP ENDEMP ON (EMP.CD_EMPRESA = ENDEMP.CD_EMPRESA)
    LEFT JOIN T_JK_LOGRADOURO LOGR ON (LOGR.CD_ENDERECO = ENDEMP.CD_ENDERECO)
    LEFT JOIN T_JK_BAIRRO BAI ON (BAI.CD_BAIRRO = LOGR.CD_BAIRRO)
    LEFT JOIN T_JK_CIDADE CID ON (CID.CD_CIDADE = BAI.CD_CIDADE)
    LEFT JOIN T_JK_ESTADO EST ON (EST.CD_ESTADO = CID.CD_ESTADO)
    LEFT JOIN T_JK_RAMO RM ON (EMP.CD_RAMO = RM.CD_RAMO)
    LEFT JOIN T_JK_FONE_EMP FNE ON (EMP.CD_EMPRESA = FNE.CD_EMPRESA)
    LEFT JOIN T_JK_FONE FN ON (FN.CD_FONE = FNE.CD_FONE)
    ORDER BY EMP.CD_EMPRESA;
    
-- RETORNA ESTADOS, CIDADES, BAIRROS E LOGRADOUROS 
    
    SELECT E.NM_ESTADO "ESTADO",
    C.NM_CIDADE "CIDADE",
    B.NM_BAIRRO "BAIRRO",
    L.NM_LOGRADOURO "LOGRADOURO"
    FROM T_JK_ESTADO E INNER JOIN T_JK_CIDADE C ON (E.CD_ESTADO = C.CD_ESTADO)
    INNER JOIN T_JK_BAIRRO B ON (B.CD_CIDADE = C.CD_CIDADE)
    INNER JOIN T_JK_LOGRADOURO L ON (L.CD_BAIRRO = B.CD_BAIRRO);
    
--RETORNAR DADOS DE PROPRIETARIOS E EMPRESAS

SELECT
    EMP.RZ_SOCIAL "EMPRESA",
    NVL(PR.NM_PROP, 'NÃO IDENTIFICADO') PROPRIETÁRIO,
    PR.QUALIFICACAO QUALIFICAÇÃO,
    NVL(TO_CHAR(PROPE.DT_INICIO), 'NÃO IDENTIFICADO') "DT VÍNCULO",
    PROPE.DT_FIM "DT FIM"
    
FROM T_JK_EMPRESA EMP
    LEFT JOIN T_JK_PROP_EMPRESA PROPE ON (EMP.CD_EMPRESA = PROPE.CD_EMPRESA)
    LEFT JOIN T_JK_PROP PR ON (PROPE.CD_PROP = PR.CD_PROP);

--RETORNAR MAQUINAS

SELECT
    MAQ.CD_MAQUINAS "CD MÁQUINA",
    MAQ.NM_MAQUINA MÁQUINA,
    CAT.DS_CATEGORIA CATEGORIA,
    EMP.RZ_SOCIAL EMPRESA,
    MAQ.STATUS STATUS,
    MAQ.FABRICANTE FABRICANTE,
    MAQ.PAIS_ORG "PAÍS ORIGEM",
    MAQ.MODELO MODELO,
    TO_DATE(MAQ.ANO_FABRIC, 'yyyy') "ANO FABRICAÇÃO",
    MAQ.VOLTAGEM VOLTAGEM,
    MAQ.NM_SERIE "NÚMERO SÉRIE"
    
FROM T_JK_MAQUINAS MAQ
    LEFT JOIN T_JK_CAT_MAQUINA CAT ON (MAQ.CD_CATEGORIA = CAT.CD_CATEGORIA)
    LEFT JOIN T_JK_EMPRESA EMP ON (MAQ.CD_EMPRESA = EMP.CD_EMPRESA);

--RETORNAR AGENDAS DE VISITA

SELECT
    AG.CD_AGENDA "CD AGENDA",
    EMP.RZ_SOCIAL "EMPRESA",
    LOGR.NM_LOGRADOURO LOGRADOURO, 
    SUBSTR( LOGR.NR_CEP , 1 , 2 ) || '.' || substr( LOGR.NR_CEP , 3 , 3) || '-' || substr( LOGR.NR_CEP , 6 , length(LOGR.NR_CEP)) AS CEP,
    END.NR_ENDERECO "NÚMERO",
    AG.EMAIL EMAIL,
    RTRIM(LTRIM(AG.TELEFONE)) TELEFONE,
    AG.DT_AGENDA "DT AGENDA",
    TO_CHAR(AG.HR_AGENDA,'HH24:MI:SS') "HR AGENDA"
    
FROM T_JK_AGENDA AG
LEFT JOIN T_JK_EMPRESA EMP ON (AG.CD_EMPRESA = EMP.CD_EMPRESA)
LEFT JOIN T_JK_LOGRADOURO LOGR ON (AG.CD_ENDERECO = LOGR.CD_ENDERECO)
LEFT JOIN T_JK_ENDERECO_EMP END ON (LOGR.CD_ENDERECO = END.CD_ENDERECO);

-- CONSULTA GERAL PARA RELACIONAR TODAS AS TABELAS DO BANCO - JK CONNECTION
-- UTILIZADA PARA GERAÇÃO DO ARQUIVO CSV

SELECT  
         EMP.CD_EMPRESA "CD EMPRESA",
         EMP.CNPJ_EMP CNPJ,
         EMP.RZ_SOCIAL "RAZÃO SOCIAL",
         EMP.NM_FANTASIA "NOME FANTASIA",
         EMP.EMAIL EMAIL,
         EMP.SITE SITE,
         '(' || RTRIM(FN.NR_DDD) || ')' || FN.NR_FONE TELEFONE,
         EMP.PORTE PORTE,
         NVL(RTRIM(LTRIM(PR.NM_PROP)), 'NÃO IDENTIFICADO') "NOME PROP",
         CASE  
         WHEN PR.GENERO_NASC = 'M' THEN 'MASCULINO'
         WHEN PR.GENERO_NASC = 'F' THEN 'FEMININO'
         ELSE 'NÃO IDENTIFICADO' END "GÊNERO",
         NVL(TO_CHAR(PROE.DT_INICIO), 'NÃO IDENTIFICADO') "DT VÍNCULO",
         PR.QUALIFICACAO QUALIFICAÇÃO,
         EMP.DT_FUNDACAO "DT FUNDAÇÃO",
         RM.NM_RAMO "RAMO",
         RM.NR_RAMO "NR RAMO",
         EMP.ENT_CLIENTE "CLIENTE/PROSPECÇÃO",
         EST.NM_ESTADO ESTADO,
         CID.NM_CIDADE CIDADE,
         RTRIM(LTRIM(BAI.NM_BAIRRO)) BAIRRO,
         LTRIM(LOGR.NM_LOGRADOURO) || ', ' || LTRIM(ENDEMP.NR_ENDERECO) || ' - ' || LTRIM(TO_CHAR(SUBSTR( LOGR.NR_CEP , 1 , 2 ) 
         || '.' || substr( LOGR.NR_CEP , 3 , 3) || '-' || substr( LOGR.NR_CEP , 6 , length(LOGR.NR_CEP)))) "ENDEREÇO",
         ENDEMP.DS_COMPLEMENTO COMPLEMENTO,
         AG.DT_AGENDA "DT AGENDA",
         TO_CHAR(AG.HR_AGENDA,'HH24:MI:SS') "HR AGENDA",
         NVL(MAQ.NM_MAQUINA, 'NÃO IDENTIFICADO') MÁQUINA,
         NVL(CAT.DS_CATEGORIA, NULL) "CAT MÁQUINA",
         CASE 
            WHEN MAQ.STATUS = 'A' THEN 'ATIVO'
            WHEN MAQ.STATUS = 'I' THEN 'INATIVO'
            ELSE NVL(MAQ.STATUS, NULL) END "STATUS MÁQUINA",
         NVL(MAQ.FABRICANTE, NULL) FABRICANTE,
         NVL(MAQ.PAIS_ORG, NULL) "PAÍS ORIGEM",
         NVL(MAQ.MODELO, NULL) MODELO,
         NVL(TO_CHAR(TO_DATE(MAQ.ANO_FABRIC, 'yyyy')),NULL) "ANO FABRICAÇÃO",
         NVL(MAQ.VOLTAGEM, NULL) VOLTAGEM,
         NVL(MAQ.NM_SERIE, NULL) "NUM SÉRIE MÁQUINA"
         
FROM T_JK_EMPRESA EMP
    LEFT JOIN T_JK_ENDERECO_EMP ENDEMP ON (EMP.CD_EMPRESA = ENDEMP.CD_EMPRESA)
    LEFT JOIN T_JK_LOGRADOURO LOGR ON (LOGR.CD_ENDERECO = ENDEMP.CD_ENDERECO)
    LEFT JOIN T_JK_BAIRRO BAI ON (BAI.CD_BAIRRO = LOGR.CD_BAIRRO)
    LEFT JOIN T_JK_CIDADE CID ON (CID.CD_CIDADE = BAI.CD_CIDADE)
    LEFT JOIN T_JK_ESTADO EST ON (EST.CD_ESTADO = CID.CD_ESTADO)
    INNER JOIN T_JK_RAMO RM ON (EMP.CD_RAMO = RM.CD_RAMO)
    INNER JOIN T_JK_AGENDA AG ON (AG.CD_EMPRESA = EMP.CD_EMPRESA)
    LEFT JOIN T_JK_MAQUINAS MAQ ON (EMP.CD_EMPRESA = MAQ.CD_EMPRESA)
    LEFT JOIN T_JK_CAT_MAQUINA CAT ON (CAT.CD_CATEGORIA = MAQ.CD_CATEGORIA)
    LEFT JOIN T_JK_FONE_EMP FNE ON (EMP.CD_EMPRESA = FNE.CD_EMPRESA)
    LEFT JOIN T_JK_FONE FN ON (FN.CD_FONE = FNE.CD_FONE)
    LEFT JOIN T_JK_PROP_EMPRESA PROE ON (EMP.CD_EMPRESA = PROE.CD_EMPRESA)
    LEFT JOIN T_JK_PROP PR ON (PROE.CD_PROP = PR.CD_PROP)
    ORDER BY EMP.CD_EMPRESA;
    



    
