-- JK AGENDA DE VISITAS - GRUPO AG - COMANDOS DDL PARA CRIAÇÃO DE ESTRUTURAS

  CREATE SEQUENCE SQ_JK_FONE
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_PROP
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_RAMO
  MINVALUE 1
  MAXVALUE 999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

  CREATE SEQUENCE SQ_JK_EMPRESA
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_CAT_MAQUINA
  MINVALUE 1
  MAXVALUE 99999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_MAQUINAS
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_AGENDA
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_VISITA
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_LOGRADOURO
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_BAIRRO
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_CIDADE
  MINVALUE 1
  MAXVALUE 99999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_ESTADO
  MINVALUE 1
  MAXVALUE 99
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SQ_JK_EQUIPAMENTO
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_JK_AGENDA (
    CD_AGENDA   NUMBER(10) NOT NULL,
    CD_EMPRESA  NUMBER(9) NOT NULL,
    CD_ENDERECO NUMBER(10) NOT NULL,
    EMAIL       VARCHAR2(80) NOT NULL,
    TELEFONE    VARCHAR2(15) NOT NULL,
    DT_AGENDA   DATE NOT NULL,
    HR_AGENDA   DATE NOT NULL,
    DESC_VISITA VARCHAR2(1000) NOT NULL
);

ALTER TABLE T_JK_AGENDA ADD CONSTRAINT JK_AGENDA_PK PRIMARY KEY ( CD_AGENDA );

CREATE TABLE T_JK_BAIRRO (
    CD_BAIRRO NUMBER(9) NOT NULL,
    CD_CIDADE NUMBER(5) NOT NULL,
    NM_BAIRRO VARCHAR2(60) NOT NULL
);

ALTER TABLE T_JK_BAIRRO ADD CONSTRAINT JK_BAIRRO_PK PRIMARY KEY ( CD_BAIRRO );

CREATE TABLE T_JK_CAT_MAQUINA (
    CD_CATEGORIA NUMBER(5) NOT NULL,
    DS_CATEGORIA VARCHAR2(40) NOT NULL,
    STATUS       CHAR(1) NOT NULL
);

ALTER TABLE T_JK_CAT_MAQUINA ADD CONSTRAINT JK_CAT_MAQUINA_PK PRIMARY KEY ( CD_CATEGORIA );

CREATE TABLE T_JK_CIDADE (
    CD_CIDADE NUMBER(5) NOT NULL,
    CD_ESTADO NUMBER(2) NOT NULL,
    NM_CIDADE VARCHAR2(50) NOT NULL
);

ALTER TABLE T_JK_CIDADE ADD CONSTRAINT JK_CIDADE_PK PRIMARY KEY ( CD_CIDADE );

CREATE TABLE T_JK_EMPRESA (
    CD_EMPRESA  NUMBER(9) NOT NULL,
    CD_RAMO     NUMBER(5) NOT NULL,
    CNPJ_EMP    VARCHAR2(18) NOT NULL,
    RZ_SOCIAL   VARCHAR2(50) NOT NULL,
    NM_FANTASIA VARCHAR2(40),
    DT_FUNDACAO DATE,
    ORIGEM_CTT  VARCHAR2(50),
    EMAIL       VARCHAR2(100),
    ENT_CLIENTE VARCHAR2(15),
    PORTE       VARCHAR2(30),
    SITE        VARCHAR2(100)
);

ALTER TABLE T_JK_EMPRESA ADD CONSTRAINT JK_EMPRESA_PK PRIMARY KEY ( CD_EMPRESA );

CREATE TABLE T_JK_ENDERECO_EMP (
    CD_EMPRESA     NUMBER(9) NOT NULL,
    CD_ENDERECO    NUMBER(10) NOT NULL,
    NR_ENDERECO    VARCHAR2(5),
    STATUS         CHAR(1) NOT NULL,
    DT_INICIO      DATE NOT NULL,
    DT_FIM         DATE,
    DS_COMPLEMENTO VARCHAR2(40)
);

ALTER TABLE T_JK_ENDERECO_EMP ADD CONSTRAINT JK_ENDERECO_EMP_PK PRIMARY KEY ( CD_EMPRESA,
                                                                                CD_ENDERECO );

CREATE TABLE T_JK_EQUIPAMENTO (
    CD_EQUIPAMENTO    NUMBER(9) NOT NULL,
    NM_EQUIPAMENTO    VARCHAR2(60) NOT NULL,
    NM_SERIE          VARCHAR2(40) NOT NULL,
    STATUS            CHAR(1) NOT NULL,
    NM_FORNECEDOR     VARCHAR2(40),
    DT_INSTALACAO     DATE NOT NULL,
    DT_FIM_INSTALACAO DATE
);

ALTER TABLE T_JK_EQUIPAMENTO ADD CONSTRAINT JK_EQUIPAMENTO_PK PRIMARY KEY ( CD_EQUIPAMENTO );

CREATE TABLE T_JK_ESTADO (
    CD_ESTADO NUMBER(2) NOT NULL,
    NM_ESTADO VARCHAR2(40) NOT NULL
);

ALTER TABLE T_JK_ESTADO ADD CONSTRAINT JK_ESTADO_PK PRIMARY KEY ( CD_ESTADO );

CREATE TABLE T_JK_FONE (
    CD_FONE  NUMBER(9) NOT NULL,
    NR_FONE  VARCHAR2(9) NOT NULL,
    NR_DDD   CHAR(3),
    OBS_FONE VARCHAR2(25)
);

ALTER TABLE T_JK_FONE ADD CONSTRAINT JK_FONE_PK PRIMARY KEY ( CD_FONE );

CREATE TABLE T_JK_FONE_EMP (
    CD_EMPRESA NUMBER(9) NOT NULL,
    CD_FONE    NUMBER(9) NOT NULL,
    DT_INICIO  DATE NOT NULL,
    DT_FIM     DATE,
    STATUS     CHAR(1) NOT NULL
);

ALTER TABLE T_JK_FONE_EMP ADD CONSTRAINT JK_FONE_EMP_PK PRIMARY KEY ( CD_EMPRESA,
                                                                        CD_FONE );

CREATE TABLE T_JK_FONE_PROP (
    CD_PROP   NUMBER(9) NOT NULL,
    CD_FONE   NUMBER(9) NOT NULL,
    DT_INICIO DATE NOT NULL,
    DT_FIM    DATE,
    STATUS    CHAR(1) NOT NULL
);

ALTER TABLE T_JK_FONE_PROP ADD CONSTRAINT JK_FONE_PROP_PK PRIMARY KEY ( CD_PROP,
                                                                          CD_FONE );

CREATE TABLE T_JK_LOGRADOURO (
    CD_ENDERECO   NUMBER(10) NOT NULL,
    CD_BAIRRO     NUMBER(9) NOT NULL,
    NM_LOGRADOURO VARCHAR2(150) NOT NULL,
    NR_CEP        VARCHAR2(8)
);

ALTER TABLE T_JK_LOGRADOURO ADD CONSTRAINT JK_LOGRADOURO_PK PRIMARY KEY ( CD_ENDERECO );

CREATE TABLE T_JK_MAQUINAS (
    CD_MAQUINAS  NUMBER(9) NOT NULL,
    CD_CATEGORIA NUMBER(5) NOT NULL,
    CD_EMPRESA   NUMBER(9) NOT NULL,
    NM_MAQUINA   VARCHAR2(70) NOT NULL,
    STATUS       CHAR(1),
    SITUACAO     VARCHAR2(30),
    FABRICANTE   VARCHAR2(50),
    PAIS_ORG     VARCHAR2(30),
    MODELO       VARCHAR2(30),
    ANO_FABRIC   DATE,
    VOLTAGEM     VARCHAR2(20),
    NM_SERIE     VARCHAR2(40)
);

ALTER TABLE T_JK_MAQUINAS ADD CONSTRAINT JK_MAQUINAS_PK PRIMARY KEY ( CD_MAQUINAS );

CREATE TABLE T_JK_PROP (
    CD_PROP      NUMBER(9) NOT NULL,
    NM_PROP      VARCHAR2(50) NOT NULL,
    DT_NASC      DATE NOT NULL,
    GENERO_NASC  CHAR(1),
    EMAIL        VARCHAR2(100),
    TELEFONE     VARCHAR2(18),
    QUALIFICACAO VARCHAR2(100)
);

ALTER TABLE T_JK_PROP ADD CONSTRAINT JK_PROP_PK PRIMARY KEY ( CD_PROP );

CREATE TABLE T_JK_PROP_EMPRESA (
    CD_PROP    NUMBER(9) NOT NULL,
    CD_EMPRESA NUMBER(9) NOT NULL,
    DT_INICIO  DATE,
    DT_FIM     DATE
);

ALTER TABLE T_JK_PROP_EMPRESA ADD CONSTRAINT JK_PROP_EMPRESA_PK PRIMARY KEY ( CD_PROP,
                                                                                CD_EMPRESA );

CREATE TABLE T_JK_RAMO (
    CD_RAMO NUMBER(5) NOT NULL,
    NM_RAMO VARCHAR2(40) NOT NULL
);

ALTER TABLE T_JK_RAMO ADD CONSTRAINT JK_RAMO_PK PRIMARY KEY ( CD_RAMO );

CREATE TABLE T_JK_VISITA (
    CD_AGENDA       NUMBER(10) NOT NULL,
    CD_VISITA       NUMBER(9) NOT NULL,
    TP_VISITA       VARCHAR2(30) NOT NULL,
    STATUS          VARCHAR2(30) NOT NULL,
    LAUDO_VISITA    CLOB NOT NULL,
    HR_INICIO       DATE NOT NULL,
    HR_FIM          DATE,
    VL_VISITA       NUMBER(9, 2),
    VL_DESCONTO     NUMBER(9, 2),
    VL_TOTAL_VISITA NUMBER(9, 2)
);

ALTER TABLE T_JK_VISITA ADD CONSTRAINT JK_VISITA_PK PRIMARY KEY ( CD_VISITA,
                                                                    CD_AGENDA );

CREATE TABLE T_JK_MAQ_EQUIP (
    CD_MAQUINAS    NUMBER(9) NOT NULL,
    CD_EQUIPAMENTO NUMBER(9) NOT NULL,
    DT_INICIO      DATE NOT NULL,
    DT_FIM         DATE,
    STATUS         CHAR(1) NOT NULL
);

ALTER TABLE T_JK_MAQ_EQUIP ADD CONSTRAINT JK_MAQ_EQUIP_PK PRIMARY KEY ( CD_MAQUINAS,
                                                                    CD_EQUIPAMENTO );

ALTER TABLE T_JK_AGENDA
    ADD CONSTRAINT JK_AGENDA_EMPRESA_FK FOREIGN KEY ( CD_EMPRESA )
        REFERENCES T_JK_EMPRESA ( CD_EMPRESA );

ALTER TABLE T_JK_AGENDA
    ADD CONSTRAINT JK_AGENDA_LOGRADOURO_FK FOREIGN KEY ( CD_ENDERECO )
        REFERENCES T_JK_LOGRADOURO ( CD_ENDERECO );

ALTER TABLE T_JK_BAIRRO
    ADD CONSTRAINT JK_BAIRRO_CIDADE_FK FOREIGN KEY ( CD_CIDADE )
        REFERENCES T_JK_CIDADE ( CD_CIDADE );

ALTER TABLE T_JK_CIDADE
    ADD CONSTRAINT JK_CIDADE_ESTADO_FK FOREIGN KEY ( CD_ESTADO )
        REFERENCES T_JK_ESTADO ( CD_ESTADO );

ALTER TABLE T_JK_EMPRESA
    ADD CONSTRAINT JK_EMPRESA_RAMO_FK FOREIGN KEY ( CD_RAMO )
        REFERENCES T_JK_RAMO ( CD_RAMO );
 
ALTER TABLE T_JK_ENDERECO_EMP
    ADD CONSTRAINT JK_ENDERECO_EMPRESA_FK FOREIGN KEY ( CD_EMPRESA )
        REFERENCES T_JK_EMPRESA ( CD_EMPRESA );

ALTER TABLE T_JK_ENDERECO_EMP
    ADD CONSTRAINT JK_END_EMPRESA_FK FOREIGN KEY ( CD_ENDERECO )
        REFERENCES T_JK_LOGRADOURO ( CD_ENDERECO );

ALTER TABLE T_JK_FONE_EMP
    ADD CONSTRAINT JK_FONE_EMPRESA_FK FOREIGN KEY ( CD_EMPRESA )
        REFERENCES T_JK_EMPRESA ( CD_EMPRESA );

ALTER TABLE T_JK_FONE_EMP
    ADD CONSTRAINT JK_FONE_EMP_FK FOREIGN KEY ( CD_FONE )
        REFERENCES T_JK_FONE ( CD_FONE );

ALTER TABLE T_JK_FONE_PROP
    ADD CONSTRAINT JK_FONE_PROP_FK FOREIGN KEY ( CD_FONE )
        REFERENCES T_JK_FONE ( CD_FONE );

ALTER TABLE T_JK_FONE_PROP
    ADD CONSTRAINT JK_PROP_FONE_FK FOREIGN KEY ( CD_PROP )
        REFERENCES T_JK_PROP ( CD_PROP );

ALTER TABLE T_JK_LOGRADOURO
    ADD CONSTRAINT JK_LOGRADOURO_BAIRRO_FK FOREIGN KEY ( CD_BAIRRO )
        REFERENCES T_JK_BAIRRO ( CD_BAIRRO );

ALTER TABLE T_JK_MAQUINAS
    ADD CONSTRAINT JK_MAQUINAS_CAT_FK FOREIGN KEY ( CD_CATEGORIA )
        REFERENCES T_JK_CAT_MAQUINA ( CD_CATEGORIA );

ALTER TABLE T_JK_MAQUINAS
    ADD CONSTRAINT JK_MAQUINAS_EMPRESA_FK FOREIGN KEY ( CD_EMPRESA )
        REFERENCES T_JK_EMPRESA ( CD_EMPRESA );

ALTER TABLE T_JK_PROP_EMPRESA
    ADD CONSTRAINT JK_PROP_EMPRESA_FK FOREIGN KEY ( CD_EMPRESA )
        REFERENCES T_JK_EMPRESA ( CD_EMPRESA );

ALTER TABLE T_JK_PROP_EMPRESA
    ADD CONSTRAINT JK_EMPRESA_PROP_FK FOREIGN KEY ( CD_PROP )
        REFERENCES T_JK_PROP ( CD_PROP );

ALTER TABLE T_JK_VISITA
    ADD CONSTRAINT JK_VISITA_AGENDA_FK FOREIGN KEY ( CD_AGENDA )
        REFERENCES T_JK_AGENDA ( CD_AGENDA );
 
ALTER TABLE T_JK_MAQ_EQUIP
    ADD CONSTRAINT JK_MAQ_EQUIP_FK FOREIGN KEY ( CD_EQUIPAMENTO )
        REFERENCES T_JK_EQUIPAMENTO ( CD_EQUIPAMENTO );

ALTER TABLE T_JK_MAQ_EQUIP
    ADD CONSTRAINT JK_EQUIP_MAQUINAS_FK FOREIGN KEY ( CD_MAQUINAS )
        REFERENCES T_JK_MAQUINAS ( CD_MAQUINAS );
        
--ALTERAÇÕES FEITAS NOS CAMPOS DAS TABELAS

ALTER TABLE T_JK_PROP 
    ADD FAIXA_ETARIA VARCHAR2(30);
    
ALTER TABLE T_JK_CIDADE 
    ADD CD_IBGE NUMERIC(8);
    
ALTER TABLE T_JK_RAMO 
    ADD NR_RAMO VARCHAR2(20);
    
ALTER TABLE T_JK_RAMO 
    MODIFY NM_RAMO VARCHAR2(140);
    
ALTER TABLE T_JK_EMPRESA 
    MODIFY RZ_SOCIAL VARCHAR2(80);
    
ALTER TABLE T_JK_EMPRESA 
    MODIFY NM_FANTASIA VARCHAR2(70);
    
ALTER TABLE T_JK_PROP
    MODIFY DT_NASC DATE NULL;
    
ALTER TABLE T_JK_CAT_MAQUINA
    MODIFY DS_CATEGORIA VARCHAR2(70);
    
ALTER TABLE T_JK_MAQUINAS 
    MODIFY ANO_FABRIC VARCHAR2(10);
    
ALTER TABLE T_JK_MAQUINAS 
    ADD CLASSIFICACAO VARCHAR2(30);
    
ALTER TABLE T_JK_AGENDA
    MODIFY DESC_VISITA VARCHAR2(1000) NULL;
    
ALTER TABLE T_JK_BAIRRO 
    MODIFY NM_BAIRRO VARCHAR2(100);
    
ALTER TABLE T_JK_ENDERECO_EMP
    MODIFY NR_ENDERECO VARCHAR2(10);
    
ALTER TABLE T_JK_MAQUINAS 
    ADD CONSTRAINT CK_JK_SITUACAO_MAQ CHECK(UPPER(SITUACAO) IN('AUTOMATIZADA','NÃO AUTOMATIZADA'));

ALTER TABLE T_JK_EQUIPAMENTO 
    ADD CONSTRAINT CK_JK_STATUS_EQUIP CHECK(UPPER(STATUS) IN('A','I'));

ALTER TABLE T_JK_CAT_MAQUINA
    ADD CONSTRAINT CK_JK_STATUS_CAT_MAQ CHECK(UPPER(STATUS) IN('A','I'));
    
ALTER TABLE T_JK_PROP
    ADD CONSTRAINT CK_JK_GENERO_PROP CHECK(UPPER(GENERO_NASC) IN('F','M','U'));
    

